### PR TITLE
Fixes for performance and valuation report deserialization

### PR DESCRIPTION
**Pull request by darayus**
Thanks for putting this library together! I noticed a few return types defined in `api_data.json` didn't match the response from the server which prevented them from being deserialized. There are probably more since I can see several `*_id` fields marked as strings, but these are the only 2 reports i've tested and can confirm as working so i've left the others unchanged for now.

### CODE REVIEW

**Comment by markcatley** [comment]
Thanks for that. Yes, their documentation on return types is not very good and it tends to require a going over to get it to work.

Do you mind adding a couple of examples so I can easily test this in the "sharesight-examples" crate. I tried to do a quick example but am still getting API errors. Not entirely sure why. I copied the "list_trades" example like so:
```rust
use clap::Parser;
use log::info;
use sharesight_examples::init_logger;
use sharesight_reqwest::Client;
use sharesight_types::{
    Performance, PerformanceParameters, PerformanceSuccess, PortfolioList, PortfolioListSuccess,
    DEFAULT_API_HOST,
};

/// List the portfolios using the Sharesight API
#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// The host to use to access the API.
    #[clap(long, default_value = DEFAULT_API_HOST)]
    api_host: String,
    /// The name of the portfolio to list.
    portfolio_name: String,
    /// The access token to use the api.
    access_token: String,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    init_logger();

    let args = Args::parse();
    let client = Client::new_with_token_and_host(args.access_token, args.api_host);
    let portfolio_name = args.portfolio_name;

    let PortfolioListSuccess { portfolios, .. } = client.execute::<PortfolioList, _>(&()).await?;

    let portfolio = portfolios.iter().find(|p| p.name == portfolio_name);

    if let Some(portfolio) = portfolio {
        info!(
            "Fetching for portfolio \"{}\" ({})",
            portfolio.name, portfolio.id
        );

        let performance_params = PerformanceParameters {
            start_date: None,
            end_date: None,
            portfolio_id: portfolio.id,
            consolidated: Some(true),
            include_sales: Some(true),
            grouping: None,
            custom_group_id: None,
        };
        let performance = client
            .execute::<Performance, PerformanceSuccess>(&performance_params)
            .await?;

        println!("{performance:?}")
    } else {
        eprint!("Unknown portfolio: {}, ", portfolio_name);

        let mut names = portfolios.iter().map(|p| p.name.as_str());

        match (names.next(), names.next_back()) {
            (Some(name_start), Some(name_end)) => {
                eprint!("the portfolios are: {}", name_start);
                for name in names {
                    eprint!(", {}", name);
                }
                eprintln!(" or {}", name_end);
            }
            (Some(name), None) => {
                eprintln!("the only portfolio is: {}", name);
            }
            (None, None) => {
                eprintln!("there are no portfolios");
            }
            _ => unreachable!(),
        }
    }

    Ok(())
}
```

**Comment by darayus** [comment]
Thanks for looking at this so quickly! Their docs could definitely use some work - they also contain types which are different to the actual returned types, so unfortunately the only way is to test it against a real portfolio. I've added a couple examples similar to the one you have above except that `consolidated` is `None`. I curiously get a 404 API error if I set `consolidated` to `true`. It should be a legal value according to [their docs](https://portfolio.sharesight.com/api/2/doc/index.html#api-User_API_Reports-Performance) so I don't really know why that is. Hopefully that works for you too.

**Comment by markcatley** [comment]
I couldn't test this due to other data issues but I'm going to merge and release this.

**Comment by darayus** [comment]
Thanks! Strange you couldn't get it to work, your portfoilio report must return different data to mine which in an unexpected format.

**Pull request merged**
